import { Verb, VerbCategory } from './types';

export const VERB_DATA: Verb[] = [
  // --- Group 1: -n Ending ---
  { base: 'do', past: 'did', participle: 'done', category: VerbCategory.N_ENDING },
  { base: 'go', past: 'went', participle: 'gone', category: VerbCategory.N_ENDING },
  { base: 'beat', past: 'beat', participle: 'beaten', category: VerbCategory.N_ENDING },
  { base: 'eat', past: 'ate', participle: 'eaten', category: VerbCategory.N_ENDING },
  { base: 'fall', past: 'fell', participle: 'fallen', category: VerbCategory.N_ENDING },
  { base: 'blow', past: 'blew', participle: 'blown', category: VerbCategory.N_ENDING },
  { base: 'draw', past: 'drew', participle: 'drawn', category: VerbCategory.N_ENDING },
  { base: 'drive', past: 'drove', participle: 'driven', category: VerbCategory.N_ENDING },
  { base: 'give', past: 'gave', participle: 'given', category: VerbCategory.N_ENDING },
  { base: 'grow', past: 'grew', participle: 'grown', category: VerbCategory.N_ENDING },
  { base: 'know', past: 'knew', participle: 'known', category: VerbCategory.N_ENDING },
  { base: 'take', past: 'took', participle: 'taken', category: VerbCategory.N_ENDING },
  { base: 'mistake', past: 'mistook', participle: 'mistaken', category: VerbCategory.N_ENDING },
  { base: 'rise', past: 'rose', participle: 'risen', category: VerbCategory.N_ENDING },
  { base: 'see', past: 'saw', participle: 'seen', category: VerbCategory.N_ENDING },
  { base: 'show', past: 'showed', participle: 'shown', category: VerbCategory.N_ENDING },
  { base: 'throw', past: 'threw', participle: 'thrown', category: VerbCategory.N_ENDING },
  { base: 'hide', past: 'hid', participle: 'hidden', category: VerbCategory.N_ENDING },
  { base: 'ride', past: 'rode', participle: 'ridden', category: VerbCategory.N_ENDING },
  { base: 'write', past: 'wrote', participle: 'written', category: VerbCategory.N_ENDING },
  { base: 'break', past: 'broke', participle: 'broken', category: VerbCategory.N_ENDING },
  { base: 'choose', past: 'chose', participle: 'chosen', category: VerbCategory.N_ENDING },
  { base: 'forget', past: 'forgot', participle: 'forgotten', category: VerbCategory.N_ENDING },
  { base: 'freeze', past: 'froze', participle: 'frozen', category: VerbCategory.N_ENDING },
  { base: 'speak', past: 'spoke', participle: 'spoken', category: VerbCategory.N_ENDING },
  { base: 'steal', past: 'stole', participle: 'stolen', category: VerbCategory.N_ENDING },
  { base: 'am / is', past: 'was', participle: 'been', category: VerbCategory.N_ENDING },
  { base: 'are', past: 'were', participle: 'been', category: VerbCategory.N_ENDING },
  { base: 'fly', past: 'flew', participle: 'flown', category: VerbCategory.N_ENDING },
  { base: 'lie', past: 'lay', participle: 'lain', category: VerbCategory.N_ENDING },
  { base: 'wear', past: 'wore', participle: 'worn', category: VerbCategory.N_ENDING },

  // --- Group 2: A-B-B (Past & Participle Same) ---
  { base: 'bring', past: 'brought', participle: 'brought', category: VerbCategory.ABB },
  { base: 'build', past: 'built', participle: 'built', category: VerbCategory.ABB },
  { base: 'buy', past: 'bought', participle: 'bought', category: VerbCategory.ABB },
  { base: 'catch', past: 'caught', participle: 'caught', category: VerbCategory.ABB },
  { base: 'dig', past: 'dug', participle: 'dug', category: VerbCategory.ABB },
  { base: 'feel', past: 'felt', participle: 'felt', category: VerbCategory.ABB },
  { base: 'find', past: 'found', participle: 'found', category: VerbCategory.ABB },
  { base: 'get', past: 'got', participle: 'got', category: VerbCategory.ABB },
  { base: 'hang', past: 'hung / hanged', participle: 'hung / hanged', category: VerbCategory.ABB },
  { base: 'have / has', past: 'had', participle: 'had', category: VerbCategory.ABB },
  { base: 'hold', past: 'held', participle: 'held', category: VerbCategory.ABB },
  { base: 'keep', past: 'kept', participle: 'kept', category: VerbCategory.ABB },
  { base: 'lay', past: 'laid', participle: 'laid', category: VerbCategory.ABB },
  { base: 'learn', past: 'learnt / learned', participle: 'learnt / learned', category: VerbCategory.ABB },
  { base: 'leave', past: 'left', participle: 'left', category: VerbCategory.ABB },
  { base: 'lend', past: 'lent', participle: 'lent', category: VerbCategory.ABB },
  { base: 'lose', past: 'lost', participle: 'lost', category: VerbCategory.ABB },
  { base: 'hear', past: 'heard', participle: 'heard', category: VerbCategory.ABB },
  { base: 'make', past: 'made', participle: 'made', category: VerbCategory.ABB },
  { base: 'mean', past: 'meant', participle: 'meant', category: VerbCategory.ABB },
  { base: 'meet', past: 'met', participle: 'met', category: VerbCategory.ABB },
  { base: 'pay', past: 'paid', participle: 'paid', category: VerbCategory.ABB },
  { base: 'say', past: 'said', participle: 'said', category: VerbCategory.ABB },
  { base: 'sell', past: 'sold', participle: 'sold', category: VerbCategory.ABB },
  { base: 'send', past: 'sent', participle: 'sent', category: VerbCategory.ABB },
  { base: 'shine', past: 'shone / shined', participle: 'shone / shined', category: VerbCategory.ABB },
  { base: 'sit', past: 'sat', participle: 'sat', category: VerbCategory.ABB },
  { base: 'sleep', past: 'slept', participle: 'slept', category: VerbCategory.ABB },
  { base: 'smell', past: 'smelt', participle: 'smelt', category: VerbCategory.ABB },
  { base: 'spend', past: 'spent', participle: 'spent', category: VerbCategory.ABB },
  { base: 'spill', past: 'spilt', participle: 'spilt', category: VerbCategory.ABB },
  { base: 'spit', past: 'spat', participle: 'spat', category: VerbCategory.ABB },
  { base: 'spoil', past: 'spoilt', participle: 'spoilt', category: VerbCategory.ABB },
  { base: 'stand', past: 'stood', participle: 'stood', category: VerbCategory.ABB },
  { base: 'sweep', past: 'swept', participle: 'swept', category: VerbCategory.ABB },
  { base: 'teach', past: 'taught', participle: 'taught', category: VerbCategory.ABB },
  { base: 'tell', past: 'told', participle: 'told', category: VerbCategory.ABB },
  { base: 'think', past: 'thought', participle: 'thought', category: VerbCategory.ABB },
  { base: 'understand', past: 'understood', participle: 'understood', category: VerbCategory.ABB },
  { base: 'wake', past: 'woke / waked', participle: 'woken / waked', category: VerbCategory.ABB }, // Note: PDF has both forms, can be tricky.
  { base: 'win', past: 'won', participle: 'won', category: VerbCategory.ABB },

  // --- Group 3: A-A-A (All Same) ---
  { base: 'cost', past: 'cost', participle: 'cost', category: VerbCategory.AAA },
  { base: 'cut', past: 'cut', participle: 'cut', category: VerbCategory.AAA },
  { base: 'hit', past: 'hit', participle: 'hit', category: VerbCategory.AAA },
  { base: 'hurt', past: 'hurt', participle: 'hurt', category: VerbCategory.AAA },
  { base: 'let', past: 'let', participle: 'let', category: VerbCategory.AAA },
  { base: 'put', past: 'put', participle: 'put', category: VerbCategory.AAA },
  { base: 'read', past: 'read', participle: 'read', category: VerbCategory.AAA }, // Note pronunciation diff in practice
  { base: 'set', past: 'set', participle: 'set', category: VerbCategory.AAA },
  { base: 'shut', past: 'shut', participle: 'shut', category: VerbCategory.AAA },

  // --- Group 4: i - a - u ---
  { base: 'begin', past: 'began', participle: 'begun', category: VerbCategory.IAU },
  { base: 'drink', past: 'drank', participle: 'drunk', category: VerbCategory.IAU },
  { base: 'ring', past: 'rang', participle: 'rung', category: VerbCategory.IAU },
  { base: 'sing', past: 'sang', participle: 'sung', category: VerbCategory.IAU },
  { base: 'sink', past: 'sank', participle: 'sunk', category: VerbCategory.IAU },
  { base: 'swim', past: 'swam', participle: 'swum', category: VerbCategory.IAU },

  // --- Group 5: A-B-A (Participle same as Base) ---
  { base: 'become', past: 'became', participle: 'become', category: VerbCategory.ABA },
  { base: 'come', past: 'came', participle: 'come', category: VerbCategory.ABA },
  { base: 'run', past: 'ran', participle: 'run', category: VerbCategory.ABA },

  // --- Group 6: Modals ---
  { base: 'can', past: 'could', participle: '-', category: VerbCategory.MODAL },
  { base: 'must', past: 'must', participle: '-', category: VerbCategory.MODAL },
  { base: 'will', past: 'would', participle: '-', category: VerbCategory.MODAL },
  { base: 'may', past: 'might', participle: '-', category: VerbCategory.MODAL },
  { base: 'shall', past: 'should', participle: '-', category: VerbCategory.MODAL },
];